SELECT MEMBER_IDX, TITLE, CONTENT, REGIST_DATE, VIEWS FROM FREEBOARD;

SELECT f.IDX, f.TITLE, f.CONTENT, f.REGIST_DATE, f.VIEWS, f.MEMBER_IDX 
    FROM FREEBOARD f JOIN MEMBER m ON f.MEMBER_IDX = m.MEMBER_IDX WHERE m.NAME LIKE '%±è%';
    
    select * from freeboard;
SELECT fb.IDX, fb.TITLE, fb.CONTENT, fb.REGIST_DATE, 
        fb.VIEWS, fb.MEMBER_IDX, m.NAME
	        FROM FREEBOARD fb
	        JOIN MEMBER m ON fb.MEMBER_IDX = m.MEMBER_IDX
            WHERE FB.IDX = 2;
            
SELECT f.IDX, f.TITLE, f.CONTENT, f.REGIST_DATE, f.VIEWS, f.MEMBER_IDX, m.NAME
        FROM FREEBOARD f LEFT JOIN MEMBER m ON f.IDX = m.MEMBER_IDX
        WHERE f.TITLE LIKE '%Ã¹%' OR f.CONTENT LIKE '%Ã¹%';

SELECT f.IDX, f.TITLE, f.CONTENT, f.REGIST_DATE, f.VIEWS, f.MEMBER_IDX, m.NAME
        FROM FREEBOARD f LEFT JOIN MEMBER m ON f.IDX = m.MEMBER_IDX WHERE m.NAME LIKE '%±è%';            
            
SELECT * FROM FREEBOARD WHERE IDX = 2;
SELECT * FROM FREEBOARD;
            